siteTitle = "Kevin To - Front-end Developer"
siteShortName = "Kevin To"
siteUrl = "https://kevinto.me"
siteDescription = "Kevin To is an experienced Front-end Developer from Sydney, Australia."
siteAuthor = "Kevin To"
siteKeyword = "Front-end Developer, Web Developer, HTML, CSS, JavaScript, Sydney, Australia"
siteImage = "/images/avatar.jpg"
siteThemeColor = "#ffffff"
twitterHandle = "qkevinto"
gaTrackingId = "UA-22787959-1"
linkPrefix = "/"
